export interface CityConfig { slug: string; display: string; state: string }
export const CITIES: CityConfig[] = [
  { slug: 'new-york', display: 'New York', state: 'NY' },
  { slug: 'los-angeles', display: 'Los Angeles', state: 'CA' },
  { slug: 'chicago', display: 'Chicago', state: 'IL' },
  { slug: 'houston', display: 'Houston', state: 'TX' },
  { slug: 'phoenix', display: 'Phoenix', state: 'AZ' },
  { slug: 'philadelphia', display: 'Philadelphia', state: 'PA' },
  { slug: 'san-antonio', display: 'San Antonio', state: 'TX' },
  { slug: 'san-diego', display: 'San Diego', state: 'CA' },
  { slug: 'dallas', display: 'Dallas', state: 'TX' },
  { slug: 'san-jose', display: 'San Jose', state: 'CA' },
  { slug: 'austin', display: 'Austin', state: 'TX' },
  { slug: 'jacksonville', display: 'Jacksonville', state: 'FL' },
  { slug: 'fort-worth', display: 'Fort Worth', state: 'TX' },
  { slug: 'columbus', display: 'Columbus', state: 'OH' },
  { slug: 'charlotte', display: 'Charlotte', state: 'NC' },
  { slug: 'indianapolis', display: 'Indianapolis', state: 'IN' },
  { slug: 'san-francisco', display: 'San Francisco', state: 'CA' },
  { slug: 'seattle', display: 'Seattle', state: 'WA' },
  { slug: 'denver', display: 'Denver', state: 'CO' },
  { slug: 'nashville', display: 'Nashville', state: 'TN' },
  { slug: 'oklahoma-city', display: 'Oklahoma City', state: 'OK' },
  { slug: 'el-paso', display: 'El Paso', state: 'TX' },
  { slug: 'washington-dc', display: 'Washington DC', state: 'DC' },
  { slug: 'las-vegas', display: 'Las Vegas', state: 'NV' },
  { slug: 'louisville', display: 'Louisville', state: 'KY' },
  { slug: 'memphis', display: 'Memphis', state: 'TN' },
  { slug: 'portland', display: 'Portland', state: 'OR' },
  { slug: 'baltimore', display: 'Baltimore', state: 'MD' },
  { slug: 'milwaukee', display: 'Milwaukee', state: 'WI' },
  { slug: 'albuquerque', display: 'Albuquerque', state: 'NM' },
  { slug: 'tucson', display: 'Tucson', state: 'AZ' },
  { slug: 'fresno', display: 'Fresno', state: 'CA' },
  { slug: 'kansas-city', display: 'Kansas City', state: 'MO' },
  { slug: 'omaha', display: 'Omaha', state: 'NE' },
  { slug: 'raleigh', display: 'Raleigh', state: 'NC' },
  { slug: 'minneapolis', display: 'Minneapolis', state: 'MN' },
  { slug: 'cleveland', display: 'Cleveland', state: 'OH' },
  { slug: 'atlanta', display: 'Atlanta', state: 'GA' },
  { slug: 'miami', display: 'Miami', state: 'FL' },
  { slug: 'new-orleans', display: 'New Orleans', state: 'LA' },
  { slug: 'detroit', display: 'Detroit', state: 'MI' },
  { slug: 'pittsburgh', display: 'Pittsburgh', state: 'PA' },
  { slug: 'salt-lake-city', display: 'Salt Lake City', state: 'UT' },
  { slug: 'tampa', display: 'Tampa', state: 'FL' },
  { slug: 'orlando', display: 'Orlando', state: 'FL' },
  { slug: 'boston', display: 'Boston', state: 'MA' },
]
export const CITY_SLUGS = CITIES.map(c => c.slug)
export function getCityBySlug(slug: string): CityConfig | undefined { return CITIES.find(c => c.slug === slug) }
export function getCityByDisplay(display: string): CityConfig | undefined { return CITIES.find(c => c.display.toLowerCase() === display.toLowerCase()) }
